/*
1Cent.Host API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onehost

import (
	"encoding/json"
)

// checks if the ServerLocationsGet200ResponseLocationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerLocationsGet200ResponseLocationsInner{}

// ServerLocationsGet200ResponseLocationsInner struct for ServerLocationsGet200ResponseLocationsInner
type ServerLocationsGet200ResponseLocationsInner struct {
	Id *int32 `json:"id,omitempty"`
	NameEn *string `json:"name_en,omitempty"`
	NameRu *string `json:"name_ru,omitempty"`
	Descr *string `json:"descr,omitempty"`
	Code *string `json:"code,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewServerLocationsGet200ResponseLocationsInner instantiates a new ServerLocationsGet200ResponseLocationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerLocationsGet200ResponseLocationsInner() *ServerLocationsGet200ResponseLocationsInner {
	this := ServerLocationsGet200ResponseLocationsInner{}
	return &this
}

// NewServerLocationsGet200ResponseLocationsInnerWithDefaults instantiates a new ServerLocationsGet200ResponseLocationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerLocationsGet200ResponseLocationsInnerWithDefaults() *ServerLocationsGet200ResponseLocationsInner {
	this := ServerLocationsGet200ResponseLocationsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServerLocationsGet200ResponseLocationsInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationsGet200ResponseLocationsInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServerLocationsGet200ResponseLocationsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ServerLocationsGet200ResponseLocationsInner) SetId(v int32) {
	o.Id = &v
}

// GetNameEn returns the NameEn field value if set, zero value otherwise.
func (o *ServerLocationsGet200ResponseLocationsInner) GetNameEn() string {
	if o == nil || IsNil(o.NameEn) {
		var ret string
		return ret
	}
	return *o.NameEn
}

// GetNameEnOk returns a tuple with the NameEn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationsGet200ResponseLocationsInner) GetNameEnOk() (*string, bool) {
	if o == nil || IsNil(o.NameEn) {
		return nil, false
	}
	return o.NameEn, true
}

// HasNameEn returns a boolean if a field has been set.
func (o *ServerLocationsGet200ResponseLocationsInner) HasNameEn() bool {
	if o != nil && !IsNil(o.NameEn) {
		return true
	}

	return false
}

// SetNameEn gets a reference to the given string and assigns it to the NameEn field.
func (o *ServerLocationsGet200ResponseLocationsInner) SetNameEn(v string) {
	o.NameEn = &v
}

// GetNameRu returns the NameRu field value if set, zero value otherwise.
func (o *ServerLocationsGet200ResponseLocationsInner) GetNameRu() string {
	if o == nil || IsNil(o.NameRu) {
		var ret string
		return ret
	}
	return *o.NameRu
}

// GetNameRuOk returns a tuple with the NameRu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationsGet200ResponseLocationsInner) GetNameRuOk() (*string, bool) {
	if o == nil || IsNil(o.NameRu) {
		return nil, false
	}
	return o.NameRu, true
}

// HasNameRu returns a boolean if a field has been set.
func (o *ServerLocationsGet200ResponseLocationsInner) HasNameRu() bool {
	if o != nil && !IsNil(o.NameRu) {
		return true
	}

	return false
}

// SetNameRu gets a reference to the given string and assigns it to the NameRu field.
func (o *ServerLocationsGet200ResponseLocationsInner) SetNameRu(v string) {
	o.NameRu = &v
}

// GetDescr returns the Descr field value if set, zero value otherwise.
func (o *ServerLocationsGet200ResponseLocationsInner) GetDescr() string {
	if o == nil || IsNil(o.Descr) {
		var ret string
		return ret
	}
	return *o.Descr
}

// GetDescrOk returns a tuple with the Descr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationsGet200ResponseLocationsInner) GetDescrOk() (*string, bool) {
	if o == nil || IsNil(o.Descr) {
		return nil, false
	}
	return o.Descr, true
}

// HasDescr returns a boolean if a field has been set.
func (o *ServerLocationsGet200ResponseLocationsInner) HasDescr() bool {
	if o != nil && !IsNil(o.Descr) {
		return true
	}

	return false
}

// SetDescr gets a reference to the given string and assigns it to the Descr field.
func (o *ServerLocationsGet200ResponseLocationsInner) SetDescr(v string) {
	o.Descr = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ServerLocationsGet200ResponseLocationsInner) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationsGet200ResponseLocationsInner) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ServerLocationsGet200ResponseLocationsInner) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ServerLocationsGet200ResponseLocationsInner) SetCode(v string) {
	o.Code = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ServerLocationsGet200ResponseLocationsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationsGet200ResponseLocationsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ServerLocationsGet200ResponseLocationsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ServerLocationsGet200ResponseLocationsInner) SetType(v string) {
	o.Type = &v
}

func (o ServerLocationsGet200ResponseLocationsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerLocationsGet200ResponseLocationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.NameEn) {
		toSerialize["name_en"] = o.NameEn
	}
	if !IsNil(o.NameRu) {
		toSerialize["name_ru"] = o.NameRu
	}
	if !IsNil(o.Descr) {
		toSerialize["descr"] = o.Descr
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableServerLocationsGet200ResponseLocationsInner struct {
	value *ServerLocationsGet200ResponseLocationsInner
	isSet bool
}

func (v NullableServerLocationsGet200ResponseLocationsInner) Get() *ServerLocationsGet200ResponseLocationsInner {
	return v.value
}

func (v *NullableServerLocationsGet200ResponseLocationsInner) Set(val *ServerLocationsGet200ResponseLocationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableServerLocationsGet200ResponseLocationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableServerLocationsGet200ResponseLocationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerLocationsGet200ResponseLocationsInner(val *ServerLocationsGet200ResponseLocationsInner) *NullableServerLocationsGet200ResponseLocationsInner {
	return &NullableServerLocationsGet200ResponseLocationsInner{value: val, isSet: true}
}

func (v NullableServerLocationsGet200ResponseLocationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerLocationsGet200ResponseLocationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


