/*
1Cent.Host API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onehost

import (
	"encoding/json"
)

// checks if the ServerServerIdGet200ResponseServer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerServerIdGet200ResponseServer{}

// ServerServerIdGet200ResponseServer struct for ServerServerIdGet200ResponseServer
type ServerServerIdGet200ResponseServer struct {
	Id *int32 `json:"id,omitempty"`
	Type *string `json:"type,omitempty"`
	Ip *string `json:"ip,omitempty"`
	Login *string `json:"login,omitempty"`
	Password *string `json:"password,omitempty"`
	Location *ServerServerIdGet200ResponseServerLocation `json:"location,omitempty"`
	Conf *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs `json:"conf,omitempty"`
	Price *float32 `json:"price,omitempty"`
	Owner *string `json:"owner,omitempty"`
	Os *string `json:"os,omitempty"`
	AutoRenew *bool `json:"auto_renew,omitempty"`
	Status *string `json:"status,omitempty"`
	Start *string `json:"start,omitempty"`
	End *string `json:"end,omitempty"`
}

// NewServerServerIdGet200ResponseServer instantiates a new ServerServerIdGet200ResponseServer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerServerIdGet200ResponseServer() *ServerServerIdGet200ResponseServer {
	this := ServerServerIdGet200ResponseServer{}
	return &this
}

// NewServerServerIdGet200ResponseServerWithDefaults instantiates a new ServerServerIdGet200ResponseServer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerServerIdGet200ResponseServerWithDefaults() *ServerServerIdGet200ResponseServer {
	this := ServerServerIdGet200ResponseServer{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ServerServerIdGet200ResponseServer) SetId(v int32) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ServerServerIdGet200ResponseServer) SetType(v string) {
	o.Type = &v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *ServerServerIdGet200ResponseServer) SetIp(v string) {
	o.Ip = &v
}

// GetLogin returns the Login field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetLogin() string {
	if o == nil || IsNil(o.Login) {
		var ret string
		return ret
	}
	return *o.Login
}

// GetLoginOk returns a tuple with the Login field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetLoginOk() (*string, bool) {
	if o == nil || IsNil(o.Login) {
		return nil, false
	}
	return o.Login, true
}

// HasLogin returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasLogin() bool {
	if o != nil && !IsNil(o.Login) {
		return true
	}

	return false
}

// SetLogin gets a reference to the given string and assigns it to the Login field.
func (o *ServerServerIdGet200ResponseServer) SetLogin(v string) {
	o.Login = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *ServerServerIdGet200ResponseServer) SetPassword(v string) {
	o.Password = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetLocation() ServerServerIdGet200ResponseServerLocation {
	if o == nil || IsNil(o.Location) {
		var ret ServerServerIdGet200ResponseServerLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetLocationOk() (*ServerServerIdGet200ResponseServerLocation, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given ServerServerIdGet200ResponseServerLocation and assigns it to the Location field.
func (o *ServerServerIdGet200ResponseServer) SetLocation(v ServerServerIdGet200ResponseServerLocation) {
	o.Location = &v
}

// GetConf returns the Conf field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetConf() ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs {
	if o == nil || IsNil(o.Conf) {
		var ret ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs
		return ret
	}
	return *o.Conf
}

// GetConfOk returns a tuple with the Conf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetConfOk() (*ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs, bool) {
	if o == nil || IsNil(o.Conf) {
		return nil, false
	}
	return o.Conf, true
}

// HasConf returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasConf() bool {
	if o != nil && !IsNil(o.Conf) {
		return true
	}

	return false
}

// SetConf gets a reference to the given ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs and assigns it to the Conf field.
func (o *ServerServerIdGet200ResponseServer) SetConf(v ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) {
	o.Conf = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *ServerServerIdGet200ResponseServer) SetPrice(v float32) {
	o.Price = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *ServerServerIdGet200ResponseServer) SetOwner(v string) {
	o.Owner = &v
}

// GetOs returns the Os field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetOs() string {
	if o == nil || IsNil(o.Os) {
		var ret string
		return ret
	}
	return *o.Os
}

// GetOsOk returns a tuple with the Os field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetOsOk() (*string, bool) {
	if o == nil || IsNil(o.Os) {
		return nil, false
	}
	return o.Os, true
}

// HasOs returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasOs() bool {
	if o != nil && !IsNil(o.Os) {
		return true
	}

	return false
}

// SetOs gets a reference to the given string and assigns it to the Os field.
func (o *ServerServerIdGet200ResponseServer) SetOs(v string) {
	o.Os = &v
}

// GetAutoRenew returns the AutoRenew field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetAutoRenew() bool {
	if o == nil || IsNil(o.AutoRenew) {
		var ret bool
		return ret
	}
	return *o.AutoRenew
}

// GetAutoRenewOk returns a tuple with the AutoRenew field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetAutoRenewOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoRenew) {
		return nil, false
	}
	return o.AutoRenew, true
}

// HasAutoRenew returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasAutoRenew() bool {
	if o != nil && !IsNil(o.AutoRenew) {
		return true
	}

	return false
}

// SetAutoRenew gets a reference to the given bool and assigns it to the AutoRenew field.
func (o *ServerServerIdGet200ResponseServer) SetAutoRenew(v bool) {
	o.AutoRenew = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ServerServerIdGet200ResponseServer) SetStatus(v string) {
	o.Status = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetStart() string {
	if o == nil || IsNil(o.Start) {
		var ret string
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetStartOk() (*string, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given string and assigns it to the Start field.
func (o *ServerServerIdGet200ResponseServer) SetStart(v string) {
	o.Start = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *ServerServerIdGet200ResponseServer) GetEnd() string {
	if o == nil || IsNil(o.End) {
		var ret string
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200ResponseServer) GetEndOk() (*string, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *ServerServerIdGet200ResponseServer) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given string and assigns it to the End field.
func (o *ServerServerIdGet200ResponseServer) SetEnd(v string) {
	o.End = &v
}

func (o ServerServerIdGet200ResponseServer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerServerIdGet200ResponseServer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Login) {
		toSerialize["login"] = o.Login
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Conf) {
		toSerialize["conf"] = o.Conf
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.Os) {
		toSerialize["os"] = o.Os
	}
	if !IsNil(o.AutoRenew) {
		toSerialize["auto_renew"] = o.AutoRenew
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	return toSerialize, nil
}

type NullableServerServerIdGet200ResponseServer struct {
	value *ServerServerIdGet200ResponseServer
	isSet bool
}

func (v NullableServerServerIdGet200ResponseServer) Get() *ServerServerIdGet200ResponseServer {
	return v.value
}

func (v *NullableServerServerIdGet200ResponseServer) Set(val *ServerServerIdGet200ResponseServer) {
	v.value = val
	v.isSet = true
}

func (v NullableServerServerIdGet200ResponseServer) IsSet() bool {
	return v.isSet
}

func (v *NullableServerServerIdGet200ResponseServer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerServerIdGet200ResponseServer(val *ServerServerIdGet200ResponseServer) *NullableServerServerIdGet200ResponseServer {
	return &NullableServerServerIdGet200ResponseServer{value: val, isSet: true}
}

func (v NullableServerServerIdGet200ResponseServer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerServerIdGet200ResponseServer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


