/*
1Cent.Host API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onehost

import (
	"encoding/json"
)

// checks if the ServerServerIdGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerServerIdGet200Response{}

// ServerServerIdGet200Response struct for ServerServerIdGet200Response
type ServerServerIdGet200Response struct {
	Server *ServerServerIdGet200ResponseServer `json:"server,omitempty"`
}

// NewServerServerIdGet200Response instantiates a new ServerServerIdGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerServerIdGet200Response() *ServerServerIdGet200Response {
	this := ServerServerIdGet200Response{}
	return &this
}

// NewServerServerIdGet200ResponseWithDefaults instantiates a new ServerServerIdGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerServerIdGet200ResponseWithDefaults() *ServerServerIdGet200Response {
	this := ServerServerIdGet200Response{}
	return &this
}

// GetServer returns the Server field value if set, zero value otherwise.
func (o *ServerServerIdGet200Response) GetServer() ServerServerIdGet200ResponseServer {
	if o == nil || IsNil(o.Server) {
		var ret ServerServerIdGet200ResponseServer
		return ret
	}
	return *o.Server
}

// GetServerOk returns a tuple with the Server field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdGet200Response) GetServerOk() (*ServerServerIdGet200ResponseServer, bool) {
	if o == nil || IsNil(o.Server) {
		return nil, false
	}
	return o.Server, true
}

// HasServer returns a boolean if a field has been set.
func (o *ServerServerIdGet200Response) HasServer() bool {
	if o != nil && !IsNil(o.Server) {
		return true
	}

	return false
}

// SetServer gets a reference to the given ServerServerIdGet200ResponseServer and assigns it to the Server field.
func (o *ServerServerIdGet200Response) SetServer(v ServerServerIdGet200ResponseServer) {
	o.Server = &v
}

func (o ServerServerIdGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerServerIdGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Server) {
		toSerialize["server"] = o.Server
	}
	return toSerialize, nil
}

type NullableServerServerIdGet200Response struct {
	value *ServerServerIdGet200Response
	isSet bool
}

func (v NullableServerServerIdGet200Response) Get() *ServerServerIdGet200Response {
	return v.value
}

func (v *NullableServerServerIdGet200Response) Set(val *ServerServerIdGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableServerServerIdGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableServerServerIdGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerServerIdGet200Response(val *ServerServerIdGet200Response) *NullableServerServerIdGet200Response {
	return &NullableServerServerIdGet200Response{value: val, isSet: true}
}

func (v NullableServerServerIdGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerServerIdGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


