/*
1Cent.Host API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onehost

import (
	"encoding/json"
)

// checks if the ServerServerIdProlongPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerServerIdProlongPost200Response{}

// ServerServerIdProlongPost200Response struct for ServerServerIdProlongPost200Response
type ServerServerIdProlongPost200Response struct {
	Message *string `json:"message,omitempty"`
	Server *ServerServerIdProlongPost200ResponseServer `json:"server,omitempty"`
}

// NewServerServerIdProlongPost200Response instantiates a new ServerServerIdProlongPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerServerIdProlongPost200Response() *ServerServerIdProlongPost200Response {
	this := ServerServerIdProlongPost200Response{}
	return &this
}

// NewServerServerIdProlongPost200ResponseWithDefaults instantiates a new ServerServerIdProlongPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerServerIdProlongPost200ResponseWithDefaults() *ServerServerIdProlongPost200Response {
	this := ServerServerIdProlongPost200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ServerServerIdProlongPost200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdProlongPost200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ServerServerIdProlongPost200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ServerServerIdProlongPost200Response) SetMessage(v string) {
	o.Message = &v
}

// GetServer returns the Server field value if set, zero value otherwise.
func (o *ServerServerIdProlongPost200Response) GetServer() ServerServerIdProlongPost200ResponseServer {
	if o == nil || IsNil(o.Server) {
		var ret ServerServerIdProlongPost200ResponseServer
		return ret
	}
	return *o.Server
}

// GetServerOk returns a tuple with the Server field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdProlongPost200Response) GetServerOk() (*ServerServerIdProlongPost200ResponseServer, bool) {
	if o == nil || IsNil(o.Server) {
		return nil, false
	}
	return o.Server, true
}

// HasServer returns a boolean if a field has been set.
func (o *ServerServerIdProlongPost200Response) HasServer() bool {
	if o != nil && !IsNil(o.Server) {
		return true
	}

	return false
}

// SetServer gets a reference to the given ServerServerIdProlongPost200ResponseServer and assigns it to the Server field.
func (o *ServerServerIdProlongPost200Response) SetServer(v ServerServerIdProlongPost200ResponseServer) {
	o.Server = &v
}

func (o ServerServerIdProlongPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerServerIdProlongPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Server) {
		toSerialize["server"] = o.Server
	}
	return toSerialize, nil
}

type NullableServerServerIdProlongPost200Response struct {
	value *ServerServerIdProlongPost200Response
	isSet bool
}

func (v NullableServerServerIdProlongPost200Response) Get() *ServerServerIdProlongPost200Response {
	return v.value
}

func (v *NullableServerServerIdProlongPost200Response) Set(val *ServerServerIdProlongPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableServerServerIdProlongPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableServerServerIdProlongPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerServerIdProlongPost200Response(val *ServerServerIdProlongPost200Response) *NullableServerServerIdProlongPost200Response {
	return &NullableServerServerIdProlongPost200Response{value: val, isSet: true}
}

func (v NullableServerServerIdProlongPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerServerIdProlongPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


