/*
1Cent.Host API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onehost

import (
	"encoding/json"
)

// checks if the ServerLocationConfigurationsGet200ResponseConfigurationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerLocationConfigurationsGet200ResponseConfigurationsInner{}

// ServerLocationConfigurationsGet200ResponseConfigurationsInner struct for ServerLocationConfigurationsGet200ResponseConfigurationsInner
type ServerLocationConfigurationsGet200ResponseConfigurationsInner struct {
	Id *int32 `json:"id,omitempty"`
	Type *string `json:"type,omitempty"`
	Location *string `json:"location,omitempty"`
	Name *string `json:"name,omitempty"`
	WindowsDisabled *bool `json:"windowsDisabled,omitempty"`
	Specs *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs `json:"specs,omitempty"`
	ShortSpecs *string `json:"short_specs,omitempty"`
	Price *float32 `json:"price,omitempty"`
}

// NewServerLocationConfigurationsGet200ResponseConfigurationsInner instantiates a new ServerLocationConfigurationsGet200ResponseConfigurationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerLocationConfigurationsGet200ResponseConfigurationsInner() *ServerLocationConfigurationsGet200ResponseConfigurationsInner {
	this := ServerLocationConfigurationsGet200ResponseConfigurationsInner{}
	return &this
}

// NewServerLocationConfigurationsGet200ResponseConfigurationsInnerWithDefaults instantiates a new ServerLocationConfigurationsGet200ResponseConfigurationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerLocationConfigurationsGet200ResponseConfigurationsInnerWithDefaults() *ServerLocationConfigurationsGet200ResponseConfigurationsInner {
	this := ServerLocationConfigurationsGet200ResponseConfigurationsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) SetId(v int32) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) SetType(v string) {
	o.Type = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) SetLocation(v string) {
	o.Location = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) SetName(v string) {
	o.Name = &v
}

// GetWindowsDisabled returns the WindowsDisabled field value if set, zero value otherwise.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetWindowsDisabled() bool {
	if o == nil || IsNil(o.WindowsDisabled) {
		var ret bool
		return ret
	}
	return *o.WindowsDisabled
}

// GetWindowsDisabledOk returns a tuple with the WindowsDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetWindowsDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.WindowsDisabled) {
		return nil, false
	}
	return o.WindowsDisabled, true
}

// HasWindowsDisabled returns a boolean if a field has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) HasWindowsDisabled() bool {
	if o != nil && !IsNil(o.WindowsDisabled) {
		return true
	}

	return false
}

// SetWindowsDisabled gets a reference to the given bool and assigns it to the WindowsDisabled field.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) SetWindowsDisabled(v bool) {
	o.WindowsDisabled = &v
}

// GetSpecs returns the Specs field value if set, zero value otherwise.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetSpecs() ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs {
	if o == nil || IsNil(o.Specs) {
		var ret ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs
		return ret
	}
	return *o.Specs
}

// GetSpecsOk returns a tuple with the Specs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetSpecsOk() (*ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs, bool) {
	if o == nil || IsNil(o.Specs) {
		return nil, false
	}
	return o.Specs, true
}

// HasSpecs returns a boolean if a field has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) HasSpecs() bool {
	if o != nil && !IsNil(o.Specs) {
		return true
	}

	return false
}

// SetSpecs gets a reference to the given ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs and assigns it to the Specs field.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) SetSpecs(v ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) {
	o.Specs = &v
}

// GetShortSpecs returns the ShortSpecs field value if set, zero value otherwise.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetShortSpecs() string {
	if o == nil || IsNil(o.ShortSpecs) {
		var ret string
		return ret
	}
	return *o.ShortSpecs
}

// GetShortSpecsOk returns a tuple with the ShortSpecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetShortSpecsOk() (*string, bool) {
	if o == nil || IsNil(o.ShortSpecs) {
		return nil, false
	}
	return o.ShortSpecs, true
}

// HasShortSpecs returns a boolean if a field has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) HasShortSpecs() bool {
	if o != nil && !IsNil(o.ShortSpecs) {
		return true
	}

	return false
}

// SetShortSpecs gets a reference to the given string and assigns it to the ShortSpecs field.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) SetShortSpecs(v string) {
	o.ShortSpecs = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInner) SetPrice(v float32) {
	o.Price = &v
}

func (o ServerLocationConfigurationsGet200ResponseConfigurationsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerLocationConfigurationsGet200ResponseConfigurationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.WindowsDisabled) {
		toSerialize["windowsDisabled"] = o.WindowsDisabled
	}
	if !IsNil(o.Specs) {
		toSerialize["specs"] = o.Specs
	}
	if !IsNil(o.ShortSpecs) {
		toSerialize["short_specs"] = o.ShortSpecs
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	return toSerialize, nil
}

type NullableServerLocationConfigurationsGet200ResponseConfigurationsInner struct {
	value *ServerLocationConfigurationsGet200ResponseConfigurationsInner
	isSet bool
}

func (v NullableServerLocationConfigurationsGet200ResponseConfigurationsInner) Get() *ServerLocationConfigurationsGet200ResponseConfigurationsInner {
	return v.value
}

func (v *NullableServerLocationConfigurationsGet200ResponseConfigurationsInner) Set(val *ServerLocationConfigurationsGet200ResponseConfigurationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableServerLocationConfigurationsGet200ResponseConfigurationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableServerLocationConfigurationsGet200ResponseConfigurationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerLocationConfigurationsGet200ResponseConfigurationsInner(val *ServerLocationConfigurationsGet200ResponseConfigurationsInner) *NullableServerLocationConfigurationsGet200ResponseConfigurationsInner {
	return &NullableServerLocationConfigurationsGet200ResponseConfigurationsInner{value: val, isSet: true}
}

func (v NullableServerLocationConfigurationsGet200ResponseConfigurationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerLocationConfigurationsGet200ResponseConfigurationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


