/*
1Cent.Host API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onehost

import (
	"encoding/json"
)

// checks if the ServerServerIdProlongPost200ResponseServer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerServerIdProlongPost200ResponseServer{}

// ServerServerIdProlongPost200ResponseServer struct for ServerServerIdProlongPost200ResponseServer
type ServerServerIdProlongPost200ResponseServer struct {
	Id *int32 `json:"id,omitempty"`
	Location *string `json:"location,omitempty"`
	Ip *string `json:"ip,omitempty"`
	Login *string `json:"login,omitempty"`
	Password *string `json:"password,omitempty"`
	EndDate *string `json:"end_date,omitempty"`
	Price *float32 `json:"price,omitempty"`
}

// NewServerServerIdProlongPost200ResponseServer instantiates a new ServerServerIdProlongPost200ResponseServer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerServerIdProlongPost200ResponseServer() *ServerServerIdProlongPost200ResponseServer {
	this := ServerServerIdProlongPost200ResponseServer{}
	return &this
}

// NewServerServerIdProlongPost200ResponseServerWithDefaults instantiates a new ServerServerIdProlongPost200ResponseServer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerServerIdProlongPost200ResponseServerWithDefaults() *ServerServerIdProlongPost200ResponseServer {
	this := ServerServerIdProlongPost200ResponseServer{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServerServerIdProlongPost200ResponseServer) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdProlongPost200ResponseServer) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServerServerIdProlongPost200ResponseServer) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ServerServerIdProlongPost200ResponseServer) SetId(v int32) {
	o.Id = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *ServerServerIdProlongPost200ResponseServer) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdProlongPost200ResponseServer) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *ServerServerIdProlongPost200ResponseServer) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *ServerServerIdProlongPost200ResponseServer) SetLocation(v string) {
	o.Location = &v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *ServerServerIdProlongPost200ResponseServer) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdProlongPost200ResponseServer) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *ServerServerIdProlongPost200ResponseServer) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *ServerServerIdProlongPost200ResponseServer) SetIp(v string) {
	o.Ip = &v
}

// GetLogin returns the Login field value if set, zero value otherwise.
func (o *ServerServerIdProlongPost200ResponseServer) GetLogin() string {
	if o == nil || IsNil(o.Login) {
		var ret string
		return ret
	}
	return *o.Login
}

// GetLoginOk returns a tuple with the Login field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdProlongPost200ResponseServer) GetLoginOk() (*string, bool) {
	if o == nil || IsNil(o.Login) {
		return nil, false
	}
	return o.Login, true
}

// HasLogin returns a boolean if a field has been set.
func (o *ServerServerIdProlongPost200ResponseServer) HasLogin() bool {
	if o != nil && !IsNil(o.Login) {
		return true
	}

	return false
}

// SetLogin gets a reference to the given string and assigns it to the Login field.
func (o *ServerServerIdProlongPost200ResponseServer) SetLogin(v string) {
	o.Login = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *ServerServerIdProlongPost200ResponseServer) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdProlongPost200ResponseServer) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *ServerServerIdProlongPost200ResponseServer) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *ServerServerIdProlongPost200ResponseServer) SetPassword(v string) {
	o.Password = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *ServerServerIdProlongPost200ResponseServer) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdProlongPost200ResponseServer) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *ServerServerIdProlongPost200ResponseServer) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *ServerServerIdProlongPost200ResponseServer) SetEndDate(v string) {
	o.EndDate = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *ServerServerIdProlongPost200ResponseServer) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerServerIdProlongPost200ResponseServer) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *ServerServerIdProlongPost200ResponseServer) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *ServerServerIdProlongPost200ResponseServer) SetPrice(v float32) {
	o.Price = &v
}

func (o ServerServerIdProlongPost200ResponseServer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerServerIdProlongPost200ResponseServer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Login) {
		toSerialize["login"] = o.Login
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	return toSerialize, nil
}

type NullableServerServerIdProlongPost200ResponseServer struct {
	value *ServerServerIdProlongPost200ResponseServer
	isSet bool
}

func (v NullableServerServerIdProlongPost200ResponseServer) Get() *ServerServerIdProlongPost200ResponseServer {
	return v.value
}

func (v *NullableServerServerIdProlongPost200ResponseServer) Set(val *ServerServerIdProlongPost200ResponseServer) {
	v.value = val
	v.isSet = true
}

func (v NullableServerServerIdProlongPost200ResponseServer) IsSet() bool {
	return v.isSet
}

func (v *NullableServerServerIdProlongPost200ResponseServer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerServerIdProlongPost200ResponseServer(val *ServerServerIdProlongPost200ResponseServer) *NullableServerServerIdProlongPost200ResponseServer {
	return &NullableServerServerIdProlongPost200ResponseServer{value: val, isSet: true}
}

func (v NullableServerServerIdProlongPost200ResponseServer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerServerIdProlongPost200ResponseServer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


