/*
1Cent.Host API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onehost

import (
	"encoding/json"
)

// checks if the ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs{}

// ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs struct for ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs
type ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs struct {
	Cpu *string `json:"cpu,omitempty"`
	Ram *string `json:"ram,omitempty"`
	Disk *string `json:"disk,omitempty"`
}

// NewServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs instantiates a new ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs() *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs {
	this := ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs{}
	return &this
}

// NewServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecsWithDefaults instantiates a new ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecsWithDefaults() *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs {
	this := ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs{}
	return &this
}

// GetCpu returns the Cpu field value if set, zero value otherwise.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) GetCpu() string {
	if o == nil || IsNil(o.Cpu) {
		var ret string
		return ret
	}
	return *o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) GetCpuOk() (*string, bool) {
	if o == nil || IsNil(o.Cpu) {
		return nil, false
	}
	return o.Cpu, true
}

// HasCpu returns a boolean if a field has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) HasCpu() bool {
	if o != nil && !IsNil(o.Cpu) {
		return true
	}

	return false
}

// SetCpu gets a reference to the given string and assigns it to the Cpu field.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) SetCpu(v string) {
	o.Cpu = &v
}

// GetRam returns the Ram field value if set, zero value otherwise.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) GetRam() string {
	if o == nil || IsNil(o.Ram) {
		var ret string
		return ret
	}
	return *o.Ram
}

// GetRamOk returns a tuple with the Ram field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) GetRamOk() (*string, bool) {
	if o == nil || IsNil(o.Ram) {
		return nil, false
	}
	return o.Ram, true
}

// HasRam returns a boolean if a field has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) HasRam() bool {
	if o != nil && !IsNil(o.Ram) {
		return true
	}

	return false
}

// SetRam gets a reference to the given string and assigns it to the Ram field.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) SetRam(v string) {
	o.Ram = &v
}

// GetDisk returns the Disk field value if set, zero value otherwise.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) GetDisk() string {
	if o == nil || IsNil(o.Disk) {
		var ret string
		return ret
	}
	return *o.Disk
}

// GetDiskOk returns a tuple with the Disk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) GetDiskOk() (*string, bool) {
	if o == nil || IsNil(o.Disk) {
		return nil, false
	}
	return o.Disk, true
}

// HasDisk returns a boolean if a field has been set.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) HasDisk() bool {
	if o != nil && !IsNil(o.Disk) {
		return true
	}

	return false
}

// SetDisk gets a reference to the given string and assigns it to the Disk field.
func (o *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) SetDisk(v string) {
	o.Disk = &v
}

func (o ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cpu) {
		toSerialize["cpu"] = o.Cpu
	}
	if !IsNil(o.Ram) {
		toSerialize["ram"] = o.Ram
	}
	if !IsNil(o.Disk) {
		toSerialize["disk"] = o.Disk
	}
	return toSerialize, nil
}

type NullableServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs struct {
	value *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs
	isSet bool
}

func (v NullableServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) Get() *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs {
	return v.value
}

func (v *NullableServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) Set(val *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) {
	v.value = val
	v.isSet = true
}

func (v NullableServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) IsSet() bool {
	return v.isSet
}

func (v *NullableServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs(val *ServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) *NullableServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs {
	return &NullableServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs{value: val, isSet: true}
}

func (v NullableServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerLocationConfigurationsGet200ResponseConfigurationsInnerSpecs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


