name: Docker Image CI

#on:
  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]

on:
  push:
    tags:
      - '*.*.*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        #- name: Build the Docker image
        #run: docker build -f ./Dockerfile -t onehost:${{ github.ref_name }} .

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
     
      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ github.ref_name }}
          labels: |
            ${{ github.repository_owner }}/${{github.repository}}:latest
            ${{ github.repository_owner }}/${{github.repository}}:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/onehost:latest
            ghcr.io/${{ github.repository_owner }}/onehost:${{ github.ref_name }}




      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            user/app:latest
            user/app:1.0.0
            ghcr.io/user/app:latest
            ghcr.io/user/app:1.0.0
    #- name: Generate artifact attestation
    #  uses: actions/attest-build-provenance@v2
    #  with:
    #    subject-name: ghcr.io/${{ github.repository }}
    #    subject-digest: ${{ steps.push.outputs.digest }}
    #    push-to-registry: true
